# Generated by Django 2.2.5 on 2020-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='员工编号'),
        ),
    ]
