# Generated by Django 2.2.5 on 2020-07-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200705_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job_status',
            field=models.BooleanField(default=True, verbose_name='员工状态'),
        ),
    ]
