# Generated by Django 2.2 on 2020-09-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('create_user', models.CharField(max_length=32, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '流程分类',
                'verbose_name_plural': '流程分类',
                'db_table': 'p_process_classify',
            },
        ),
    ]
