# Generated by Django 2.2 on 2020-09-20 02:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_tplinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TplData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('form_structure', jsonfield.fields.JSONField(default=dict, verbose_name='表单结构')),
                ('form_data', models.CharField(max_length=128, unique=True, verbose_name='表单数据')),
            ],
            options={
                'verbose_name': '工单绑定模版数据',
                'verbose_name_plural': '工单绑定模版数据',
                'db_table': 'p_work_order_tpl_data',
            },
        ),
    ]
