# Generated by Django 2.2 on 2020-09-20 02:13

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_tpldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='工单标题')),
                ('priority', models.CharField(max_length=255, unique=True, verbose_name='工单优先级 1，正常 2，紧急 3，非常紧急')),
                ('process', models.CharField(max_length=255, unique=True, verbose_name='流程ID')),
                ('IsEnd', models.IntegerField(default=0, verbose_name='是否结束， 0 未结束，1 已结束')),
                ('IsDenied', models.IntegerField(default=0, verbose_name='是否被拒绝， 0 没有，1 有')),
                ('state', jsonfield.fields.JSONField(default=dict, verbose_name='状态信息')),
                ('related_person', jsonfield.fields.JSONField(default=dict, verbose_name='工单所有处理人')),
                ('create_user', models.CharField(max_length=128, unique=True, verbose_name='创建者')),
                ('urge_count', models.IntegerField(default=0, verbose_name='催办次数')),
                ('urge_last_time', models.IntegerField(default=0, verbose_name='上一次催促时间')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Classify', verbose_name='分类ID')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'p_work_order_info',
            },
        ),
    ]
