# Generated by Django 2.2 on 2020-09-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_workorderinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='任务名称')),
                ('task_type', models.CharField(max_length=100, verbose_name='任务类型')),
                ('content', models.CharField(max_length=255, verbose_name='任务内容')),
                ('create_user', models.CharField(max_length=128, unique=True, verbose_name='创建者')),
                ('remarks', models.CharField(max_length=250, unique=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'p_task_info',
            },
        ),
    ]
