# Generated by Django 2.2 on 2020-09-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_circulationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '历史', 'verbose_name_plural': '历史'},
        ),
    ]
