# Generated by Django 2.2 on 2020-09-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tplinfo',
            options={'verbose_name': '模板管理', 'verbose_name_plural': '模板管理'},
        ),
    ]
