# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-05 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
    ]
