# Generated by Django 2.2.5 on 2020-07-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200705_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
