# Generated by Django 2.2.5 on 2020-07-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200705_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
