# Generated by Django 2.2.13 on 2020-07-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200711_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='员工号'),
        ),
    ]
