# Generated by Django 2.2 on 2020-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200708_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
