# Generated by Django 2.2 on 2020-07-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200708_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
