# Generated by Django 2.2 on 2020-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200707_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(max_length=30, null=True, verbose_name='员工编号'),
        ),
    ]
