# Generated by Django 2.2.13 on 2020-07-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
    ]
