# Generated by Django 2.2.13 on 2020-07-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200709_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
        migrations.AddField(
            model_name='publisher',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
