# Generated by Django 2.2.13 on 2020-07-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200711_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
