# Generated by Django 2.2 on 2020-08-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=32)),
                ('v0', models.CharField(max_length=32)),
                ('v1', models.CharField(max_length=32)),
                ('v2', models.CharField(max_length=32)),
                ('v3', models.CharField(max_length=32)),
                ('v4', models.CharField(max_length=32)),
                ('v5', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '权限系统',
                'verbose_name_plural': '权限系统',
                'db_table': 'casbin',
            },
        ),
    ]
