# Generated by Django 2.2 on 2020-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casbinrule',
            name='v3',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='v4',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='v5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
