# Generated by Django 2.2 on 2020-08-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_auto_20200802_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casbinrule',
            name='v2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
