# Generated by Django 2.2 on 2020-08-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_auto_20200802_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casbinrule',
            options={'verbose_name': 'RESTful权限系统', 'verbose_name_plural': 'RESTful权限系统'},
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='ptype',
            field=models.CharField(choices=[('p', 'p'), ('g', 'g')], max_length=1, verbose_name='p | g'),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='v0',
            field=models.CharField(max_length=32, verbose_name='用户组 | 用户'),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='v1',
            field=models.CharField(max_length=32, verbose_name='PATH | 用户组'),
        ),
        migrations.AlterField(
            model_name='casbinrule',
            name='v2',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='METHOD'),
        ),
        migrations.AlterModelTable(
            name='casbinrule',
            table='casbin_rule',
        ),
    ]
