# Generated by Django 2.2 on 2020-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200709_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
    ]
