# Generated by Django 2.2 on 2020-07-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_auto_20200719_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(db_constraint=False, default=14, on_delete=django.db.models.deletion.DO_NOTHING, to='book.Publisher', verbose_name='出版社'),
        ),
    ]
