# Generated by Django 2.2 on 2020-07-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20200719_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.Publisher', verbose_name='出版社'),
        ),
    ]
