# Generated by Django 2.2 on 2020-08-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20200719_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='地址'),
        ),
    ]
