# Generated by Django 2.2 on 2020-08-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_auto_20200802_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
    ]
