# Generated by Django 2.2 on 2020-08-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_auto_20200802_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(default='beijing', max_length=100, verbose_name='地址'),
            preserve_default=False,
        ),
    ]
