# Generated by Django 2.2 on 2020-07-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
    ]
