# Generated by Django 2.2 on 2020-07-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200707_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
