# Generated by Django 2.2 on 2020-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200707_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
