# Generated by Django 2.2 on 2020-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=32, verbose_name='图书名称'),
        ),
    ]
