# Generated by Django 2.2 on 2020-07-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200705_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
