# Generated by Django 2.2 on 2020-07-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
