# Generated by Django 2.2 on 2020-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='评论'),
        ),
    ]
