# Generated by Django 2.2 on 2020-07-05 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200705_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社-定制', 'verbose_name_plural': '出版社-定制'},
        ),
        migrations.AddField(
            model_name='publisher',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(max_length=100, verbose_name='出版社地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=32, verbose_name='出版社名称'),
        ),
    ]
