# Generated by Django 2.2 on 2020-07-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_publisher_update_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
    ]
