# Generated by Django 2.2 on 2020-07-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社1', 'verbose_name_plural': '出版社1'},
        ),
        migrations.AddField(
            model_name='publisher',
            name='postcode',
            field=models.CharField(default=10010, max_length=10, verbose_name='邮编'),
            preserve_default=False,
        ),
    ]
